### ISSUE TITLE
Carthage build on Swift 2.3 fails

### ISSUE THREAD

**Issue by aphorisme** [Moya/Moya#642]
Hey! I'm trying to get Moya via Carthage as part of the following Cartfile: 

```
github "thoughtbot/Argo"
github "thoughtbot/Curry"
github "thoughtbot/Runes"
github "ReactiveX/RxSwift" ~> 2.0
github "Moya/Moya" ~> 7.0
```

Tried it on XCode 7.3 first, meanwhile upgraded to XCode 8 (because of Swift 2.3). I'm running 

``` bash
carthage update --no-use-binaries --toolchain com.apple.dt.toolchain.Swift_2_3 --platform mac
```

which gives me back

```
<..>/Carthage/Checkouts/Moya/Source/RxSwift/Moya+RxSwift.swift:2:8: error: module file's minimum deployment target is OS X v10.10: <..>/Carthage/Checkouts/Moya/Carthage/Build/Mac/RxSwift.framework/Modules/RxSwift.swiftmodule/x86_64.swiftmodule
<..>/Carthage/Checkouts/Moya/Source/RxSwift/Moya+RxSwift.swift:2:8: error: module file's minimum deployment target is OS X v10.10: <..>/Carthage/Checkouts/Moya/Carthage/Build/Mac/RxSwift.framework/Modules/RxSwift.swiftmodule/x86_64.swiftmodule
<..>/Carthage/Checkouts/Moya/Source/RxSwift/Moya+RxSwift.swift:2:8: error: module file's minimum deployment target is OS X v10.10: <..>/Carthage/Checkouts/Moya/Carthage/Build/Mac/RxSwift.framework/Modules/RxSwift.swiftmodule/x86_64.swiftmodule
<..>/Carthage/Checkouts/Moya/Source/RxSwift/Moya+RxSwift.swift:2:8: error: module file's minimum deployment target is OS X v10.10: <..>/Carthage/Checkouts/Moya/Carthage/Build/Mac/RxSwift.framework/Modules/RxSwift.swiftmodule/x86_64.swiftmodule
A shell task (/usr/bin/xcrun xcodebuild -project <..>/Carthage/Checkouts/Moya/Moya.xcodeproj -scheme RxMoya OSX -configuration Release -toolchain com.apple.dt.toolchain.Swift_2_3 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** BUILD FAILED **

```

Hence I've opened the Moya project file, changed the deployments targets to 10.10 (in all OSX targets) and run

``` bash
carthage build --toolchain com.apple.dt.toolchain.Swift_2_3 --platform mac
```

This returns

```
<..>/Carthage/Checkouts/Moya/Source/Error.swift:12:18: error: use of undeclared type 'RxMoya'
<..>/Carthage/Checkouts/Moya/Source/Error.swift:12:18: error: use of undeclared type 'RxMoya'
<..>/Carthage/Checkouts/Moya/Source/Error.swift:12:18: error: use of undeclared type 'RxMoya'
<..>/Carthage/Checkouts/Moya/Source/Error.swift:12:18: error: use of undeclared type 'RxMoya'
<..>/Carthage/Checkouts/Moya/Source/Plugins/NetworkActivityPlugin.swift:27:51: error: use of undeclared type 'RxMoya'
<..>/Carthage/Checkouts/Moya/Source/Moya.swift:66:17: error: use of undeclared type 'RxMoya'
<..>/Carthage/Checkouts/Moya/Source/Moya.swift:66:17: error: use of undeclared type 'RxMoya'
<..>/Carthage/Checkouts/Moya/Source/Plugin.swift:15:44: error: use of undeclared type 'RxMoya'
A shell task (/usr/bin/xcrun xcodebuild -project <..>/Carthage/Checkouts/Moya/Moya.xcodeproj -scheme Moya OSX -configuration Release -toolchain com.apple.dt.toolchain.Swift_2_3 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** BUILD FAILED **
```

Removing all those occurences gives the next error, something with `RxRxReactiveMoya` etc.

The `carthage update` at first was on a clean directory. No build directory, no checkouts.

Thanks in advance for having a look.

**Comment by tpesce** [comment]
The OS X 10.0 issue is the same thing I ran into here #636, but I didn't include OS target change with my other changes because I wasn't clear on the overall impact to the project.

For this issue, could the problem be an incompatibility between the version of RxSwift that you specify in your Cartfile (~> 2.0) and the one that Moya specifies (~> 2.6)? I ask because I created a sample OS X project, created a Cartfile with just Moya (~> 7.0), and after making the same changed you did to update the Moya OS X target to 10.0 my build was successful with:

```
carthage build --platform mac
```

**Comment by aphorisme** [comment]
[Sorry for my late response]

Running a `carthage build --platform mac` after updating without version constraints on `RxSwift` and changing the deployment target to `10.10` gives me errors of the form 

```
<..>/Carthage/Checkouts/Moya/Source/Error.swift:12:18: error: use of undeclared type 'RxReactiveRxMoya'
public extension RxReactiveRxMoya.Error {
```

I'm wondering where this `RxReactiveRxMoya` namespace is coming from.   :/

**Comment by BasThomas** [comment]
Is this issue still present in the latest release, @aphorisme?

**Comment by aphorisme** [comment]
Hey,

I’m sorry but I’ve stopped using Moya.  : /. In fact I’ve stopped using Swift… for the next months until some standardized package manager appears.  ; )

**Comment by BasThomas** [comment]
@AndrewSB, any idea if this is still an issue?

**Comment by ashfurrow** [comment]
We haven't heard from other users that this is persisting, going to close for now but we can revisit if it comes up again.
