### ISSUE TITLE
ReactiveMoya cannot build on Xcode7.1

### ISSUE THREAD

**Issue by midori2012** [Moya/Moya#268]
I am trying to update Moya  via Carthage then I find I cannot build on Xcode7.1.:cry:
Does anyoune get the same build error with the latest version 4.0.3? 
Any help or tips would be grateful!
```
*** Building scheme "ReactiveMoya" in Demo.xcworkspace
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
$(SRCROOT)/Carthage/Checkouts/Moya/Demo/Pods/ReactiveCocoa/ReactiveCocoa/ReactiveCocoa.h:67:10: error: include of non-modular header inside framework module 'ReactiveCocoa.ReactiveCocoa'
  ... 
A shell task failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
	CompileSwift normal x86_64 $(SRCROOT)/Carthage/Checkouts/Moya/Demo/Pods/ReactiveCocoa/ReactiveCocoa/Swift/Action.swift
	CompileSwift normal x86_64 $(SRCROOT)/Carthage/Checkouts/Moya/Demo/Pods/ReactiveCocoa/ReactiveCocoa/Swift/Atomic.swift
	CompileSwift normal x86_64 $(SRCROOT)/Carthage/Checkouts/Moya/Demo/Pods/ReactiveCocoa/ReactiveCocoa/Swift/Bag.swift
	CompileSwift normal x86_64 $(SRCROOT)/Carthage/Checkouts/Moya/Demo/Pods/ReactiveCocoa/ReactiveCocoa/Swift/Disposable.swift
	CompileSwift normal x86_64 $(SRCROOT)/Carthage/Checkouts/Moya/Demo/Pods/ReactiveCocoa/ReactiveCocoa/Swift/Errors.swift
	CompileSwift normal x86_64 $(SRCROOT)/Carthage/Checkouts/Moya/Demo/Pods/ReactiveCocoa/ReactiveCocoa/Swift/Event.swift
	CompileSwift normal x86_64 $(SRCROOT)/Carthage/Checkouts/Moya/Demo/Pods/ReactiveCocoa/ReactiveCocoa/Swift/FoundationExtensions.swift
	CompileSwift normal x86_64 $(SRCROOT)/Carthage/Checkouts/Moya/Demo/Pods/ReactiveCocoa/ReactiveCocoa/Swift/ObjectiveCBridging.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(9 failures)
```

**Comment by petester42** [comment]
It's already in the works #263

**Comment by midori2012** [comment]
Oh, I miss it! Thank you for letting me know:smiley:
Hope the pull req merge soon!  
Thanx
